import type { StyleSpecification } from 'maplibre-gl';

// Кастомный векторный стиль карты Loci — на базе бесплатных тайлов OpenFreeMap
// (без ключа, без лимитов: https://openfreemap.org) и открытого стиля Positron,
// перекрашенного в палитру бренда (cream/navy/gold) и очищенного от подписей,
// POI-иконок, границ и прочего шума — оставлены только фон, вода, зелень,
// застройка и дороги. Свои маркеры/попапы рисуются поверх через Leaflet.
export const lociMapStyle: StyleSpecification = {
  version: 8,
  name: 'CIS.PR Loci',
  sources: {
    openmaptiles: {
      type: 'vector',
      url: 'https://tiles.openfreemap.org/planet',
    },
  },
  glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
  layers: [
    { id: 'background', type: 'background', paint: { 'background-color': '#F4F1E9' } },
    {
      id: 'park',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'park',
      filter: ['match', ['geometry-type'], ['MultiPolygon', 'Polygon'], true, false],
      paint: { 'fill-color': '#E6E4D3' },
    },
    {
      id: 'water',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: [
        'all',
        ['match', ['geometry-type'], ['MultiPolygon', 'Polygon'], true, false],
        ['!=', ['get', 'brunnel'], 'tunnel'],
      ],
      paint: { 'fill-antialias': true, 'fill-color': '#DCE1E6' },
    },
    {
      id: 'landuse_residential',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      maxzoom: 16,
      filter: [
        'all',
        ['match', ['geometry-type'], ['MultiPolygon', 'Polygon'], true, false],
        ['==', ['get', 'class'], 'residential'],
      ],
      paint: {
        'fill-color': '#EFEAD9',
        'fill-opacity': ['interpolate', ['exponential', 0.6], ['zoom'], 8, 0.8, 9, 0.6],
      },
    },
    {
      id: 'landcover_wood',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      minzoom: 10,
      filter: [
        'all',
        ['match', ['geometry-type'], ['MultiPolygon', 'Polygon'], true, false],
        ['==', ['get', 'class'], 'wood'],
      ],
      paint: {
        'fill-color': '#E1E1CC',
        'fill-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0, 12, 1],
      },
    },
    {
      id: 'waterway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
      paint: { 'line-color': '#DCE1E6' },
    },
    {
      id: 'building',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 12,
      paint: { 'fill-antialias': true, 'fill-color': '#EAE2CC' },
    },
    {
      id: 'road_area_pier',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['match', ['geometry-type'], ['MultiPolygon', 'Polygon'], true, false],
        ['==', ['get', 'class'], 'pier'],
      ],
      paint: { 'fill-antialias': true, 'fill-color': '#E7E0CC' },
    },
    {
      id: 'road_pier',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['match', ['get', 'class'], ['pier'], true, false],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#E7E0CC',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15, 1, 17, 4],
      },
    },
    {
      id: 'highway_path',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['==', ['get', 'class'], 'path'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#E7E0CC',
        'line-opacity': 0.9,
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 13, 1, 20, 10],
      },
    },
    {
      id: 'highway_minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['match', ['get', 'class'], ['minor', 'service', 'track'], true, false],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#E7E0CC',
        'line-opacity': 0.9,
        'line-width': ['interpolate', ['exponential', 1.55], ['zoom'], 13, 1.8, 20, 20],
      },
    },
    {
      id: 'highway_major_casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 11,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['match', ['get', 'class'], ['primary', 'secondary', 'tertiary', 'trunk'], true, false],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': '#B89968',
        'line-dasharray': [12, 0],
        'line-width': ['interpolate', ['exponential', 1.3], ['zoom'], 10, 3, 20, 23],
      },
    },
    {
      id: 'highway_major_inner',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 11,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['match', ['get', 'class'], ['primary', 'secondary', 'tertiary', 'trunk'], true, false],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#D8C49E',
        'line-width': ['interpolate', ['exponential', 1.3], ['zoom'], 10, 2, 20, 20],
      },
    },
    {
      id: 'highway_major_subtle',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      maxzoom: 11,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['match', ['get', 'class'], ['primary', 'secondary', 'tertiary', 'trunk'], true, false],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': '#D8C49E', 'line-width': 2 },
    },
    {
      id: 'highway_motorway_casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 6,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        [
          'all',
          ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
          ['==', ['get', 'class'], 'motorway'],
        ],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': '#A9895E',
        'line-dasharray': [2, 0],
        'line-opacity': 1,
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 5.8, 0, 6, 3, 20, 40],
      },
    },
    {
      id: 'highway_motorway_inner',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 6,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        [
          'all',
          ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
          ['==', ['get', 'class'], 'motorway'],
        ],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#B89968',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 4, 2, 6, 1.3, 20, 30],
      },
    },
    {
      id: 'highway_motorway_subtle',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      maxzoom: 6,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['==', ['get', 'class'], 'motorway'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#B89968',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 4, 2, 6, 1.3],
      },
    },
    {
      id: 'railway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['all', ['!', ['has', 'service']], ['==', ['get', 'class'], 'rail']],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#C9BFA6',
        'line-width': ['interpolate', ['exponential', 1.3], ['zoom'], 16, 3, 20, 7],
      },
    },
    {
      id: 'highway_motorway_bridge_casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 6,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['all', ['==', ['get', 'brunnel'], 'bridge'], ['==', ['get', 'class'], 'motorway']],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': '#A9895E',
        'line-dasharray': [2, 0],
        'line-opacity': 1,
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 5.8, 0, 6, 5, 20, 45],
      },
    },
    {
      id: 'highway_motorway_bridge_inner',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 6,
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['all', ['==', ['get', 'brunnel'], 'bridge'], ['==', ['get', 'class'], 'motorway']],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#B89968',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 4, 2, 6, 1.3, 20, 30],
      },
    },
  ],
};
